// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dto/asset_trade_response_dto.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public interface AssetTradeResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.protos.AssetTradeResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string asset = 2;</code>
   * @return Whether the asset field is set.
   */
  boolean hasAsset();
  /**
   * <code>optional string asset = 2;</code>
   * @return The asset.
   */
  java.lang.String getAsset();
  /**
   * <code>optional string asset = 2;</code>
   * @return The bytes for asset.
   */
  com.google.protobuf.ByteString
      getAssetBytes();

  /**
   * <code>optional string quantity_in_g = 3;</code>
   * @return Whether the quantityInG field is set.
   */
  boolean hasQuantityInG();
  /**
   * <code>optional string quantity_in_g = 3;</code>
   * @return The quantityInG.
   */
  java.lang.String getQuantityInG();
  /**
   * <code>optional string quantity_in_g = 3;</code>
   * @return The bytes for quantityInG.
   */
  com.google.protobuf.ByteString
      getQuantityInGBytes();

  /**
   * <code>optional string asset_value = 4;</code>
   * @return Whether the assetValue field is set.
   */
  boolean hasAssetValue();
  /**
   * <code>optional string asset_value = 4;</code>
   * @return The assetValue.
   */
  java.lang.String getAssetValue();
  /**
   * <code>optional string asset_value = 4;</code>
   * @return The bytes for assetValue.
   */
  com.google.protobuf.ByteString
      getAssetValueBytes();
}
