// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dto/asset_trade_response_dto.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public final class AssetTradeResponseDTOOuterClass {
  private AssetTradeResponseDTOOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AssetTradeResponseDTOOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_protos_AssetTradeResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_protos_AssetTradeResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"dto/asset_trade_response_dto.proto\022\027co" +
      "m.example.demo.protos\"\261\001\n\025AssetTradeResp" +
      "onseDTO\022\025\n\010username\030\001 \001(\tH\000\210\001\001\022\022\n\005asset\030" +
      "\002 \001(\tH\001\210\001\001\022\032\n\rquantity_in_g\030\003 \001(\tH\002\210\001\001\022\030" +
      "\n\013asset_value\030\004 \001(\tH\003\210\001\001B\013\n\t_usernameB\010\n" +
      "\006_assetB\020\n\016_quantity_in_gB\016\n\014_asset_valu" +
      "eB<\n\027com.example.demo.protosB\037AssetTrade" +
      "ResponseDTOOuterClassP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_protos_AssetTradeResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_protos_AssetTradeResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_protos_AssetTradeResponseDTO_descriptor,
        new java.lang.String[] { "Username", "Asset", "QuantityInG", "AssetValue", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
