// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/example/demo/proto/AssetPrices.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public final class AssetPrices {
  private AssetPrices() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AssetPrices.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_protos_AssetPricesProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_protos_AssetPricesProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(com/example/demo/proto/AssetPrices.pro" +
      "to\022\027com.example.demo.protos\032\037google/prot" +
      "obuf/timestamp.proto\"\326\001\n\020AssetPricesProt" +
      "o\022\022\n\005asset\030\001 \001(\tH\000\210\001\001\022\020\n\003ask\030\002 \001(\001H\001\210\001\001\022" +
      "\020\n\003bid\030\003 \001(\001H\002\210\001\001\022\030\n\013weight_unit\030\004 \001(\tH\003" +
      "\210\001\001\0225\n\014last_updated\030\005 \001(\0132\032.google.proto" +
      "buf.TimestampH\004\210\001\001B\010\n\006_assetB\006\n\004_askB\006\n\004" +
      "_bidB\016\n\014_weight_unitB\017\n\r_last_updatedB\033\n" +
      "\027com.example.demo.protosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_demo_protos_AssetPricesProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_protos_AssetPricesProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_protos_AssetPricesProto_descriptor,
        new java.lang.String[] { "Asset", "Ask", "Bid", "WeightUnit", "LastUpdated", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
