// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity/asset_buy_request_entity.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public interface AssetBuyRequestEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.protos.AssetBuyRequestEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 5;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 5;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 5;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional double amount_deduct = 6;</code>
   * @return Whether the amountDeduct field is set.
   */
  boolean hasAmountDeduct();
  /**
   * <code>optional double amount_deduct = 6;</code>
   * @return The amountDeduct.
   */
  double getAmountDeduct();

  /**
   * <code>optional double weight_gain = 7;</code>
   * @return Whether the weightGain field is set.
   */
  boolean hasWeightGain();
  /**
   * <code>optional double weight_gain = 7;</code>
   * @return The weightGain.
   */
  double getWeightGain();

  /**
   * <code>optional string asset = 1;</code>
   * @return Whether the asset field is set.
   */
  boolean hasAsset();
  /**
   * <code>optional string asset = 1;</code>
   * @return The asset.
   */
  java.lang.String getAsset();
  /**
   * <code>optional string asset = 1;</code>
   * @return The bytes for asset.
   */
  com.google.protobuf.ByteString
      getAssetBytes();

  /**
   * <code>optional string currency = 2;</code>
   * @return Whether the currency field is set.
   */
  boolean hasCurrency();
  /**
   * <code>optional string currency = 2;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>optional string currency = 2;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>optional string weight_unit = 3;</code>
   * @return Whether the weightUnit field is set.
   */
  boolean hasWeightUnit();
  /**
   * <code>optional string weight_unit = 3;</code>
   * @return The weightUnit.
   */
  java.lang.String getWeightUnit();
  /**
   * <code>optional string weight_unit = 3;</code>
   * @return The bytes for weightUnit.
   */
  com.google.protobuf.ByteString
      getWeightUnitBytes();

  /**
   * <code>optional double quantity = 4;</code>
   * @return Whether the quantity field is set.
   */
  boolean hasQuantity();
  /**
   * <code>optional double quantity = 4;</code>
   * @return The quantity.
   */
  double getQuantity();
}
