// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dto/asset_trade_request_dto.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

/**
 * Protobuf type {@code com.example.demo.protos.AssetTradeRequestDTO}
 */
public final class AssetTradeRequestDTO extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.protos.AssetTradeRequestDTO)
    AssetTradeRequestDTOOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AssetTradeRequestDTO.class.getName());
  }
  // Use AssetTradeRequestDTO.newBuilder() to construct.
  private AssetTradeRequestDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AssetTradeRequestDTO() {
    asset_ = "";
    currency_ = "";
    weightUnit_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.protos.AssetTradeRequestDTOOuterClass.internal_static_com_example_demo_protos_AssetTradeRequestDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.protos.AssetTradeRequestDTOOuterClass.internal_static_com_example_demo_protos_AssetTradeRequestDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.protos.AssetTradeRequestDTO.class, com.example.demo.protos.AssetTradeRequestDTO.Builder.class);
  }

  private int bitField0_;
  public static final int ASSET_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object asset_ = "";
  /**
   * <code>optional string asset = 1;</code>
   * @return Whether the asset field is set.
   */
  @java.lang.Override
  public boolean hasAsset() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string asset = 1;</code>
   * @return The asset.
   */
  @java.lang.Override
  public java.lang.String getAsset() {
    java.lang.Object ref = asset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      asset_ = s;
      return s;
    }
  }
  /**
   * <code>optional string asset = 1;</code>
   * @return The bytes for asset.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssetBytes() {
    java.lang.Object ref = asset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      asset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currency_ = "";
  /**
   * <code>optional string currency = 2;</code>
   * @return Whether the currency field is set.
   */
  @java.lang.Override
  public boolean hasCurrency() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string currency = 2;</code>
   * @return The currency.
   */
  @java.lang.Override
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <code>optional string currency = 2;</code>
   * @return The bytes for currency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHT_UNIT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object weightUnit_ = "";
  /**
   * <code>optional string weight_unit = 3;</code>
   * @return Whether the weightUnit field is set.
   */
  @java.lang.Override
  public boolean hasWeightUnit() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string weight_unit = 3;</code>
   * @return The weightUnit.
   */
  @java.lang.Override
  public java.lang.String getWeightUnit() {
    java.lang.Object ref = weightUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      weightUnit_ = s;
      return s;
    }
  }
  /**
   * <code>optional string weight_unit = 3;</code>
   * @return The bytes for weightUnit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWeightUnitBytes() {
    java.lang.Object ref = weightUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      weightUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private double quantity_ = 0D;
  /**
   * <code>optional double quantity = 4;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional double quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public double getQuantity() {
    return quantity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, asset_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, currency_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, weightUnit_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeDouble(4, quantity_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, asset_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, currency_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, weightUnit_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, quantity_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.protos.AssetTradeRequestDTO)) {
      return super.equals(obj);
    }
    com.example.demo.protos.AssetTradeRequestDTO other = (com.example.demo.protos.AssetTradeRequestDTO) obj;

    if (hasAsset() != other.hasAsset()) return false;
    if (hasAsset()) {
      if (!getAsset()
          .equals(other.getAsset())) return false;
    }
    if (hasCurrency() != other.hasCurrency()) return false;
    if (hasCurrency()) {
      if (!getCurrency()
          .equals(other.getCurrency())) return false;
    }
    if (hasWeightUnit() != other.hasWeightUnit()) return false;
    if (hasWeightUnit()) {
      if (!getWeightUnit()
          .equals(other.getWeightUnit())) return false;
    }
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (java.lang.Double.doubleToLongBits(getQuantity())
          != java.lang.Double.doubleToLongBits(
              other.getQuantity())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAsset()) {
      hash = (37 * hash) + ASSET_FIELD_NUMBER;
      hash = (53 * hash) + getAsset().hashCode();
    }
    if (hasCurrency()) {
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
    }
    if (hasWeightUnit()) {
      hash = (37 * hash) + WEIGHT_UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getWeightUnit().hashCode();
    }
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQuantity()));
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.protos.AssetTradeRequestDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.protos.AssetTradeRequestDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protos.AssetTradeRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.protos.AssetTradeRequestDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.protos.AssetTradeRequestDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.protos.AssetTradeRequestDTO)
      com.example.demo.protos.AssetTradeRequestDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protos.AssetTradeRequestDTOOuterClass.internal_static_com_example_demo_protos_AssetTradeRequestDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protos.AssetTradeRequestDTOOuterClass.internal_static_com_example_demo_protos_AssetTradeRequestDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protos.AssetTradeRequestDTO.class, com.example.demo.protos.AssetTradeRequestDTO.Builder.class);
    }

    // Construct using com.example.demo.protos.AssetTradeRequestDTO.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      asset_ = "";
      currency_ = "";
      weightUnit_ = "";
      quantity_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.protos.AssetTradeRequestDTOOuterClass.internal_static_com_example_demo_protos_AssetTradeRequestDTO_descriptor;
    }

    @java.lang.Override
    public com.example.demo.protos.AssetTradeRequestDTO getDefaultInstanceForType() {
      return com.example.demo.protos.AssetTradeRequestDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.protos.AssetTradeRequestDTO build() {
      com.example.demo.protos.AssetTradeRequestDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.protos.AssetTradeRequestDTO buildPartial() {
      com.example.demo.protos.AssetTradeRequestDTO result = new com.example.demo.protos.AssetTradeRequestDTO(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.protos.AssetTradeRequestDTO result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.asset_ = asset_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.currency_ = currency_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.weightUnit_ = weightUnit_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quantity_ = quantity_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.protos.AssetTradeRequestDTO) {
        return mergeFrom((com.example.demo.protos.AssetTradeRequestDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.protos.AssetTradeRequestDTO other) {
      if (other == com.example.demo.protos.AssetTradeRequestDTO.getDefaultInstance()) return this;
      if (other.hasAsset()) {
        asset_ = other.asset_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasCurrency()) {
        currency_ = other.currency_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasWeightUnit()) {
        weightUnit_ = other.weightUnit_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              asset_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              currency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              weightUnit_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 33: {
              quantity_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object asset_ = "";
    /**
     * <code>optional string asset = 1;</code>
     * @return Whether the asset field is set.
     */
    public boolean hasAsset() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string asset = 1;</code>
     * @return The asset.
     */
    public java.lang.String getAsset() {
      java.lang.Object ref = asset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string asset = 1;</code>
     * @return The bytes for asset.
     */
    public com.google.protobuf.ByteString
        getAssetBytes() {
      java.lang.Object ref = asset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string asset = 1;</code>
     * @param value The asset to set.
     * @return This builder for chaining.
     */
    public Builder setAsset(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      asset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string asset = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsset() {
      asset_ = getDefaultInstance().getAsset();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string asset = 1;</code>
     * @param value The bytes for asset to set.
     * @return This builder for chaining.
     */
    public Builder setAssetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      asset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <code>optional string currency = 2;</code>
     * @return Whether the currency field is set.
     */
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string currency = 2;</code>
     * @return The currency.
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string currency = 2;</code>
     * @return The bytes for currency.
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string currency = 2;</code>
     * @param value The currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string currency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrency() {
      currency_ = getDefaultInstance().getCurrency();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string currency = 2;</code>
     * @param value The bytes for currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object weightUnit_ = "";
    /**
     * <code>optional string weight_unit = 3;</code>
     * @return Whether the weightUnit field is set.
     */
    public boolean hasWeightUnit() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string weight_unit = 3;</code>
     * @return The weightUnit.
     */
    public java.lang.String getWeightUnit() {
      java.lang.Object ref = weightUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weightUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string weight_unit = 3;</code>
     * @return The bytes for weightUnit.
     */
    public com.google.protobuf.ByteString
        getWeightUnitBytes() {
      java.lang.Object ref = weightUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weightUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string weight_unit = 3;</code>
     * @param value The weightUnit to set.
     * @return This builder for chaining.
     */
    public Builder setWeightUnit(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      weightUnit_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string weight_unit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightUnit() {
      weightUnit_ = getDefaultInstance().getWeightUnit();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string weight_unit = 3;</code>
     * @param value The bytes for weightUnit to set.
     * @return This builder for chaining.
     */
    public Builder setWeightUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      weightUnit_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private double quantity_ ;
    /**
     * <code>optional double quantity = 4;</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public double getQuantity() {
      return quantity_;
    }
    /**
     * <code>optional double quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(double value) {

      quantity_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional double quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      quantity_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.protos.AssetTradeRequestDTO)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.protos.AssetTradeRequestDTO)
  private static final com.example.demo.protos.AssetTradeRequestDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.protos.AssetTradeRequestDTO();
  }

  public static com.example.demo.protos.AssetTradeRequestDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetTradeRequestDTO>
      PARSER = new com.google.protobuf.AbstractParser<AssetTradeRequestDTO>() {
    @java.lang.Override
    public AssetTradeRequestDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AssetTradeRequestDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetTradeRequestDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.protos.AssetTradeRequestDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

