// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/example/demo/proto/AssetPrices.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

/**
 * Protobuf type {@code com.example.demo.protos.AssetPricesProto}
 */
public final class AssetPricesProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.protos.AssetPricesProto)
    AssetPricesProtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AssetPricesProto.class.getName());
  }
  // Use AssetPricesProto.newBuilder() to construct.
  private AssetPricesProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AssetPricesProto() {
    asset_ = "";
    weightUnit_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.protos.AssetPrices.internal_static_com_example_demo_protos_AssetPricesProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.protos.AssetPrices.internal_static_com_example_demo_protos_AssetPricesProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.protos.AssetPricesProto.class, com.example.demo.protos.AssetPricesProto.Builder.class);
  }

  private int bitField0_;
  public static final int ASSET_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object asset_ = "";
  /**
   * <code>optional string asset = 1;</code>
   * @return Whether the asset field is set.
   */
  @java.lang.Override
  public boolean hasAsset() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string asset = 1;</code>
   * @return The asset.
   */
  @java.lang.Override
  public java.lang.String getAsset() {
    java.lang.Object ref = asset_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      asset_ = s;
      return s;
    }
  }
  /**
   * <code>optional string asset = 1;</code>
   * @return The bytes for asset.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssetBytes() {
    java.lang.Object ref = asset_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      asset_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASK_FIELD_NUMBER = 2;
  private double ask_ = 0D;
  /**
   * <code>optional double ask = 2;</code>
   * @return Whether the ask field is set.
   */
  @java.lang.Override
  public boolean hasAsk() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional double ask = 2;</code>
   * @return The ask.
   */
  @java.lang.Override
  public double getAsk() {
    return ask_;
  }

  public static final int BID_FIELD_NUMBER = 3;
  private double bid_ = 0D;
  /**
   * <code>optional double bid = 3;</code>
   * @return Whether the bid field is set.
   */
  @java.lang.Override
  public boolean hasBid() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional double bid = 3;</code>
   * @return The bid.
   */
  @java.lang.Override
  public double getBid() {
    return bid_;
  }

  public static final int WEIGHT_UNIT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object weightUnit_ = "";
  /**
   * <code>optional string weight_unit = 4;</code>
   * @return Whether the weightUnit field is set.
   */
  @java.lang.Override
  public boolean hasWeightUnit() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string weight_unit = 4;</code>
   * @return The weightUnit.
   */
  @java.lang.Override
  public java.lang.String getWeightUnit() {
    java.lang.Object ref = weightUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      weightUnit_ = s;
      return s;
    }
  }
  /**
   * <code>optional string weight_unit = 4;</code>
   * @return The bytes for weightUnit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWeightUnitBytes() {
    java.lang.Object ref = weightUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      weightUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp lastUpdated_;
  /**
   * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdated() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdated() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, asset_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeDouble(2, ask_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(3, bid_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, weightUnit_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getLastUpdated());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, asset_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, ask_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, bid_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, weightUnit_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLastUpdated());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.protos.AssetPricesProto)) {
      return super.equals(obj);
    }
    com.example.demo.protos.AssetPricesProto other = (com.example.demo.protos.AssetPricesProto) obj;

    if (hasAsset() != other.hasAsset()) return false;
    if (hasAsset()) {
      if (!getAsset()
          .equals(other.getAsset())) return false;
    }
    if (hasAsk() != other.hasAsk()) return false;
    if (hasAsk()) {
      if (java.lang.Double.doubleToLongBits(getAsk())
          != java.lang.Double.doubleToLongBits(
              other.getAsk())) return false;
    }
    if (hasBid() != other.hasBid()) return false;
    if (hasBid()) {
      if (java.lang.Double.doubleToLongBits(getBid())
          != java.lang.Double.doubleToLongBits(
              other.getBid())) return false;
    }
    if (hasWeightUnit() != other.hasWeightUnit()) return false;
    if (hasWeightUnit()) {
      if (!getWeightUnit()
          .equals(other.getWeightUnit())) return false;
    }
    if (hasLastUpdated() != other.hasLastUpdated()) return false;
    if (hasLastUpdated()) {
      if (!getLastUpdated()
          .equals(other.getLastUpdated())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAsset()) {
      hash = (37 * hash) + ASSET_FIELD_NUMBER;
      hash = (53 * hash) + getAsset().hashCode();
    }
    if (hasAsk()) {
      hash = (37 * hash) + ASK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAsk()));
    }
    if (hasBid()) {
      hash = (37 * hash) + BID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBid()));
    }
    if (hasWeightUnit()) {
      hash = (37 * hash) + WEIGHT_UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getWeightUnit().hashCode();
    }
    if (hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.protos.AssetPricesProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.protos.AssetPricesProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.protos.AssetPricesProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protos.AssetPricesProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.protos.AssetPricesProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.protos.AssetPricesProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.protos.AssetPricesProto)
      com.example.demo.protos.AssetPricesProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protos.AssetPrices.internal_static_com_example_demo_protos_AssetPricesProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protos.AssetPrices.internal_static_com_example_demo_protos_AssetPricesProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protos.AssetPricesProto.class, com.example.demo.protos.AssetPricesProto.Builder.class);
    }

    // Construct using com.example.demo.protos.AssetPricesProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLastUpdatedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      asset_ = "";
      ask_ = 0D;
      bid_ = 0D;
      weightUnit_ = "";
      lastUpdated_ = null;
      if (lastUpdatedBuilder_ != null) {
        lastUpdatedBuilder_.dispose();
        lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.protos.AssetPrices.internal_static_com_example_demo_protos_AssetPricesProto_descriptor;
    }

    @java.lang.Override
    public com.example.demo.protos.AssetPricesProto getDefaultInstanceForType() {
      return com.example.demo.protos.AssetPricesProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.protos.AssetPricesProto build() {
      com.example.demo.protos.AssetPricesProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.protos.AssetPricesProto buildPartial() {
      com.example.demo.protos.AssetPricesProto result = new com.example.demo.protos.AssetPricesProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.protos.AssetPricesProto result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.asset_ = asset_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ask_ = ask_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.bid_ = bid_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.weightUnit_ = weightUnit_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastUpdated_ = lastUpdatedBuilder_ == null
            ? lastUpdated_
            : lastUpdatedBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.protos.AssetPricesProto) {
        return mergeFrom((com.example.demo.protos.AssetPricesProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.protos.AssetPricesProto other) {
      if (other == com.example.demo.protos.AssetPricesProto.getDefaultInstance()) return this;
      if (other.hasAsset()) {
        asset_ = other.asset_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasAsk()) {
        setAsk(other.getAsk());
      }
      if (other.hasBid()) {
        setBid(other.getBid());
      }
      if (other.hasWeightUnit()) {
        weightUnit_ = other.weightUnit_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              asset_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 17: {
              ask_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              bid_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              weightUnit_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getLastUpdatedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object asset_ = "";
    /**
     * <code>optional string asset = 1;</code>
     * @return Whether the asset field is set.
     */
    public boolean hasAsset() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string asset = 1;</code>
     * @return The asset.
     */
    public java.lang.String getAsset() {
      java.lang.Object ref = asset_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asset_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string asset = 1;</code>
     * @return The bytes for asset.
     */
    public com.google.protobuf.ByteString
        getAssetBytes() {
      java.lang.Object ref = asset_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string asset = 1;</code>
     * @param value The asset to set.
     * @return This builder for chaining.
     */
    public Builder setAsset(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      asset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string asset = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsset() {
      asset_ = getDefaultInstance().getAsset();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string asset = 1;</code>
     * @param value The bytes for asset to set.
     * @return This builder for chaining.
     */
    public Builder setAssetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      asset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private double ask_ ;
    /**
     * <code>optional double ask = 2;</code>
     * @return Whether the ask field is set.
     */
    @java.lang.Override
    public boolean hasAsk() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional double ask = 2;</code>
     * @return The ask.
     */
    @java.lang.Override
    public double getAsk() {
      return ask_;
    }
    /**
     * <code>optional double ask = 2;</code>
     * @param value The ask to set.
     * @return This builder for chaining.
     */
    public Builder setAsk(double value) {

      ask_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional double ask = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsk() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ask_ = 0D;
      onChanged();
      return this;
    }

    private double bid_ ;
    /**
     * <code>optional double bid = 3;</code>
     * @return Whether the bid field is set.
     */
    @java.lang.Override
    public boolean hasBid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double bid = 3;</code>
     * @return The bid.
     */
    @java.lang.Override
    public double getBid() {
      return bid_;
    }
    /**
     * <code>optional double bid = 3;</code>
     * @param value The bid to set.
     * @return This builder for chaining.
     */
    public Builder setBid(double value) {

      bid_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional double bid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      bid_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object weightUnit_ = "";
    /**
     * <code>optional string weight_unit = 4;</code>
     * @return Whether the weightUnit field is set.
     */
    public boolean hasWeightUnit() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string weight_unit = 4;</code>
     * @return The weightUnit.
     */
    public java.lang.String getWeightUnit() {
      java.lang.Object ref = weightUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weightUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string weight_unit = 4;</code>
     * @return The bytes for weightUnit.
     */
    public com.google.protobuf.ByteString
        getWeightUnitBytes() {
      java.lang.Object ref = weightUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weightUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string weight_unit = 4;</code>
     * @param value The weightUnit to set.
     * @return This builder for chaining.
     */
    public Builder setWeightUnit(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      weightUnit_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string weight_unit = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightUnit() {
      weightUnit_ = getDefaultInstance().getWeightUnit();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string weight_unit = 4;</code>
     * @param value The bytes for weightUnit to set.
     * @return This builder for chaining.
     */
    public Builder setWeightUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      weightUnit_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     * @return Whether the lastUpdated field is set.
     */
    public boolean hasLastUpdated() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     * @return The lastUpdated.
     */
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          lastUpdated_ != null &&
          lastUpdated_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getLastUpdatedBuilder().mergeFrom(value);
        } else {
          lastUpdated_ = value;
        }
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }
      if (lastUpdated_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder clearLastUpdated() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastUpdated_ = null;
      if (lastUpdatedBuilder_ != null) {
        lastUpdatedBuilder_.dispose();
        lastUpdatedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.protos.AssetPricesProto)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.protos.AssetPricesProto)
  private static final com.example.demo.protos.AssetPricesProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.protos.AssetPricesProto();
  }

  public static com.example.demo.protos.AssetPricesProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssetPricesProto>
      PARSER = new com.google.protobuf.AbstractParser<AssetPricesProto>() {
    @java.lang.Override
    public AssetPricesProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AssetPricesProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AssetPricesProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.protos.AssetPricesProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

