// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity/asset_buy_request_entity.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public final class AssetBuyRequestEntityOuterClass {
  private AssetBuyRequestEntityOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AssetBuyRequestEntityOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_protos_AssetBuyRequestEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_protos_AssetBuyRequestEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%entity/asset_buy_request_entity.proto\022" +
      "\027com.example.demo.protos\"\243\002\n\025AssetBuyReq" +
      "uestEntity\022\025\n\010username\030\005 \001(\tH\000\210\001\001\022\032\n\ramo" +
      "unt_deduct\030\006 \001(\001H\001\210\001\001\022\030\n\013weight_gain\030\007 \001" +
      "(\001H\002\210\001\001\022\022\n\005asset\030\001 \001(\tH\003\210\001\001\022\025\n\010currency\030" +
      "\002 \001(\tH\004\210\001\001\022\030\n\013weight_unit\030\003 \001(\tH\005\210\001\001\022\025\n\010" +
      "quantity\030\004 \001(\001H\006\210\001\001B\013\n\t_usernameB\020\n\016_amo" +
      "unt_deductB\016\n\014_weight_gainB\010\n\006_assetB\013\n\t" +
      "_currencyB\016\n\014_weight_unitB\013\n\t_quantityB<" +
      "\n\027com.example.demo.protosB\037AssetBuyReque" +
      "stEntityOuterClassP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_protos_AssetBuyRequestEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_protos_AssetBuyRequestEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_protos_AssetBuyRequestEntity_descriptor,
        new java.lang.String[] { "Username", "AmountDeduct", "WeightGain", "Asset", "Currency", "WeightUnit", "Quantity", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
