// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: com/example/demo/proto/AssetPrices.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public interface AssetPricesProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.protos.AssetPricesProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string asset = 1;</code>
   * @return Whether the asset field is set.
   */
  boolean hasAsset();
  /**
   * <code>optional string asset = 1;</code>
   * @return The asset.
   */
  java.lang.String getAsset();
  /**
   * <code>optional string asset = 1;</code>
   * @return The bytes for asset.
   */
  com.google.protobuf.ByteString
      getAssetBytes();

  /**
   * <code>optional double ask = 2;</code>
   * @return Whether the ask field is set.
   */
  boolean hasAsk();
  /**
   * <code>optional double ask = 2;</code>
   * @return The ask.
   */
  double getAsk();

  /**
   * <code>optional double bid = 3;</code>
   * @return Whether the bid field is set.
   */
  boolean hasBid();
  /**
   * <code>optional double bid = 3;</code>
   * @return The bid.
   */
  double getBid();

  /**
   * <code>optional string weight_unit = 4;</code>
   * @return Whether the weightUnit field is set.
   */
  boolean hasWeightUnit();
  /**
   * <code>optional string weight_unit = 4;</code>
   * @return The weightUnit.
   */
  java.lang.String getWeightUnit();
  /**
   * <code>optional string weight_unit = 4;</code>
   * @return The bytes for weightUnit.
   */
  com.google.protobuf.ByteString
      getWeightUnitBytes();

  /**
   * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>optional .google.protobuf.Timestamp last_updated = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
