// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: record/real_prices_record.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public final class RealPricesRecordOuterClass {
  private RealPricesRecordOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RealPricesRecordOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_protos_RealPricesRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_protos_RealPricesRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037record/real_prices_record.proto\022\027com.e" +
      "xample.demo.protos\032\037google/protobuf/time" +
      "stamp.proto\"\212\002\n\020RealPricesRecord\022-\n\004date" +
      "\030\001 \001(\0132\032.google.protobuf.TimestampH\000\210\001\001\022" +
      "\030\n\013weight_unit\030\002 \001(\tH\001\210\001\001\022\020\n\003ask\030\003 \001(\001H\002" +
      "\210\001\001\022\020\n\003mid\030\004 \001(\001H\003\210\001\001\022\020\n\003bid\030\005 \001(\001H\004\210\001\001\022" +
      "\022\n\005value\030\006 \001(\001H\005\210\001\001\022\030\n\013performance\030\007 \001(\001" +
      "H\006\210\001\001B\007\n\005_dateB\016\n\014_weight_unitB\006\n\004_askB\006" +
      "\n\004_midB\006\n\004_bidB\010\n\006_valueB\016\n\014_performance" +
      "B7\n\027com.example.demo.protosB\032RealPricesR" +
      "ecordOuterClassP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_demo_protos_RealPricesRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_protos_RealPricesRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_protos_RealPricesRecord_descriptor,
        new java.lang.String[] { "Date", "WeightUnit", "Ask", "Mid", "Bid", "Value", "Performance", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
