// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: record/real_prices_record.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public interface RealPricesRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.protos.RealPricesRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .google.protobuf.Timestamp date = 1;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>optional .google.protobuf.Timestamp date = 1;</code>
   * @return The date.
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>optional .google.protobuf.Timestamp date = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>optional string weight_unit = 2;</code>
   * @return Whether the weightUnit field is set.
   */
  boolean hasWeightUnit();
  /**
   * <code>optional string weight_unit = 2;</code>
   * @return The weightUnit.
   */
  java.lang.String getWeightUnit();
  /**
   * <code>optional string weight_unit = 2;</code>
   * @return The bytes for weightUnit.
   */
  com.google.protobuf.ByteString
      getWeightUnitBytes();

  /**
   * <code>optional double ask = 3;</code>
   * @return Whether the ask field is set.
   */
  boolean hasAsk();
  /**
   * <code>optional double ask = 3;</code>
   * @return The ask.
   */
  double getAsk();

  /**
   * <code>optional double mid = 4;</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <code>optional double mid = 4;</code>
   * @return The mid.
   */
  double getMid();

  /**
   * <code>optional double bid = 5;</code>
   * @return Whether the bid field is set.
   */
  boolean hasBid();
  /**
   * <code>optional double bid = 5;</code>
   * @return The bid.
   */
  double getBid();

  /**
   * <code>optional double value = 6;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>optional double value = 6;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>optional double performance = 7;</code>
   * @return Whether the performance field is set.
   */
  boolean hasPerformance();
  /**
   * <code>optional double performance = 7;</code>
   * @return The performance.
   */
  double getPerformance();
}
