// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: record/real_prices_record.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

/**
 * Protobuf type {@code com.example.demo.protos.RealPricesRecord}
 */
public final class RealPricesRecord extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.protos.RealPricesRecord)
    RealPricesRecordOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RealPricesRecord.class.getName());
  }
  // Use RealPricesRecord.newBuilder() to construct.
  private RealPricesRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RealPricesRecord() {
    weightUnit_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.protos.RealPricesRecordOuterClass.internal_static_com_example_demo_protos_RealPricesRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.protos.RealPricesRecordOuterClass.internal_static_com_example_demo_protos_RealPricesRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.protos.RealPricesRecord.class, com.example.demo.protos.RealPricesRecord.Builder.class);
  }

  private int bitField0_;
  public static final int DATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp date_;
  /**
   * <code>optional .google.protobuf.Timestamp date = 1;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp date = 1;</code>
   * @return The date.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDate() {
    return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp date = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
    return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
  }

  public static final int WEIGHT_UNIT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object weightUnit_ = "";
  /**
   * <code>optional string weight_unit = 2;</code>
   * @return Whether the weightUnit field is set.
   */
  @java.lang.Override
  public boolean hasWeightUnit() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string weight_unit = 2;</code>
   * @return The weightUnit.
   */
  @java.lang.Override
  public java.lang.String getWeightUnit() {
    java.lang.Object ref = weightUnit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      weightUnit_ = s;
      return s;
    }
  }
  /**
   * <code>optional string weight_unit = 2;</code>
   * @return The bytes for weightUnit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWeightUnitBytes() {
    java.lang.Object ref = weightUnit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      weightUnit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASK_FIELD_NUMBER = 3;
  private double ask_ = 0D;
  /**
   * <code>optional double ask = 3;</code>
   * @return Whether the ask field is set.
   */
  @java.lang.Override
  public boolean hasAsk() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional double ask = 3;</code>
   * @return The ask.
   */
  @java.lang.Override
  public double getAsk() {
    return ask_;
  }

  public static final int MID_FIELD_NUMBER = 4;
  private double mid_ = 0D;
  /**
   * <code>optional double mid = 4;</code>
   * @return Whether the mid field is set.
   */
  @java.lang.Override
  public boolean hasMid() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional double mid = 4;</code>
   * @return The mid.
   */
  @java.lang.Override
  public double getMid() {
    return mid_;
  }

  public static final int BID_FIELD_NUMBER = 5;
  private double bid_ = 0D;
  /**
   * <code>optional double bid = 5;</code>
   * @return Whether the bid field is set.
   */
  @java.lang.Override
  public boolean hasBid() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional double bid = 5;</code>
   * @return The bid.
   */
  @java.lang.Override
  public double getBid() {
    return bid_;
  }

  public static final int VALUE_FIELD_NUMBER = 6;
  private double value_ = 0D;
  /**
   * <code>optional double value = 6;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional double value = 6;</code>
   * @return The value.
   */
  @java.lang.Override
  public double getValue() {
    return value_;
  }

  public static final int PERFORMANCE_FIELD_NUMBER = 7;
  private double performance_ = 0D;
  /**
   * <code>optional double performance = 7;</code>
   * @return Whether the performance field is set.
   */
  @java.lang.Override
  public boolean hasPerformance() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional double performance = 7;</code>
   * @return The performance.
   */
  @java.lang.Override
  public double getPerformance() {
    return performance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, weightUnit_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeDouble(3, ask_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeDouble(4, mid_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeDouble(5, bid_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeDouble(6, value_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeDouble(7, performance_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, weightUnit_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, ask_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, mid_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, bid_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, value_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, performance_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.protos.RealPricesRecord)) {
      return super.equals(obj);
    }
    com.example.demo.protos.RealPricesRecord other = (com.example.demo.protos.RealPricesRecord) obj;

    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (hasWeightUnit() != other.hasWeightUnit()) return false;
    if (hasWeightUnit()) {
      if (!getWeightUnit()
          .equals(other.getWeightUnit())) return false;
    }
    if (hasAsk() != other.hasAsk()) return false;
    if (hasAsk()) {
      if (java.lang.Double.doubleToLongBits(getAsk())
          != java.lang.Double.doubleToLongBits(
              other.getAsk())) return false;
    }
    if (hasMid() != other.hasMid()) return false;
    if (hasMid()) {
      if (java.lang.Double.doubleToLongBits(getMid())
          != java.lang.Double.doubleToLongBits(
              other.getMid())) return false;
    }
    if (hasBid() != other.hasBid()) return false;
    if (hasBid()) {
      if (java.lang.Double.doubleToLongBits(getBid())
          != java.lang.Double.doubleToLongBits(
              other.getBid())) return false;
    }
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
    }
    if (hasPerformance() != other.hasPerformance()) return false;
    if (hasPerformance()) {
      if (java.lang.Double.doubleToLongBits(getPerformance())
          != java.lang.Double.doubleToLongBits(
              other.getPerformance())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    if (hasWeightUnit()) {
      hash = (37 * hash) + WEIGHT_UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getWeightUnit().hashCode();
    }
    if (hasAsk()) {
      hash = (37 * hash) + ASK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAsk()));
    }
    if (hasMid()) {
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMid()));
    }
    if (hasBid()) {
      hash = (37 * hash) + BID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBid()));
    }
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
    }
    if (hasPerformance()) {
      hash = (37 * hash) + PERFORMANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPerformance()));
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.protos.RealPricesRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.protos.RealPricesRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.protos.RealPricesRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protos.RealPricesRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.protos.RealPricesRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.protos.RealPricesRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.protos.RealPricesRecord)
      com.example.demo.protos.RealPricesRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protos.RealPricesRecordOuterClass.internal_static_com_example_demo_protos_RealPricesRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protos.RealPricesRecordOuterClass.internal_static_com_example_demo_protos_RealPricesRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protos.RealPricesRecord.class, com.example.demo.protos.RealPricesRecord.Builder.class);
    }

    // Construct using com.example.demo.protos.RealPricesRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      date_ = null;
      if (dateBuilder_ != null) {
        dateBuilder_.dispose();
        dateBuilder_ = null;
      }
      weightUnit_ = "";
      ask_ = 0D;
      mid_ = 0D;
      bid_ = 0D;
      value_ = 0D;
      performance_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.protos.RealPricesRecordOuterClass.internal_static_com_example_demo_protos_RealPricesRecord_descriptor;
    }

    @java.lang.Override
    public com.example.demo.protos.RealPricesRecord getDefaultInstanceForType() {
      return com.example.demo.protos.RealPricesRecord.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.protos.RealPricesRecord build() {
      com.example.demo.protos.RealPricesRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.protos.RealPricesRecord buildPartial() {
      com.example.demo.protos.RealPricesRecord result = new com.example.demo.protos.RealPricesRecord(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.protos.RealPricesRecord result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.date_ = dateBuilder_ == null
            ? date_
            : dateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.weightUnit_ = weightUnit_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ask_ = ask_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mid_ = mid_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bid_ = bid_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.value_ = value_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.performance_ = performance_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.protos.RealPricesRecord) {
        return mergeFrom((com.example.demo.protos.RealPricesRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.protos.RealPricesRecord other) {
      if (other == com.example.demo.protos.RealPricesRecord.getDefaultInstance()) return this;
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.hasWeightUnit()) {
        weightUnit_ = other.weightUnit_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasAsk()) {
        setAsk(other.getAsk());
      }
      if (other.hasMid()) {
        setMid(other.getMid());
      }
      if (other.hasBid()) {
        setBid(other.getBid());
      }
      if (other.hasValue()) {
        setValue(other.getValue());
      }
      if (other.hasPerformance()) {
        setPerformance(other.getPerformance());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              weightUnit_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              ask_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              mid_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              bid_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              value_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              performance_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp date_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     * @return The date.
     */
    public com.google.protobuf.Timestamp getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    public Builder setDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
      } else {
        dateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    public Builder setDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    public Builder mergeDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          date_ != null &&
          date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDateBuilder().mergeFrom(value);
        } else {
          date_ = value;
        }
      } else {
        dateBuilder_.mergeFrom(value);
      }
      if (date_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    public Builder clearDate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      date_ = null;
      if (dateBuilder_ != null) {
        dateBuilder_.dispose();
        dateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp date = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private java.lang.Object weightUnit_ = "";
    /**
     * <code>optional string weight_unit = 2;</code>
     * @return Whether the weightUnit field is set.
     */
    public boolean hasWeightUnit() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string weight_unit = 2;</code>
     * @return The weightUnit.
     */
    public java.lang.String getWeightUnit() {
      java.lang.Object ref = weightUnit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weightUnit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string weight_unit = 2;</code>
     * @return The bytes for weightUnit.
     */
    public com.google.protobuf.ByteString
        getWeightUnitBytes() {
      java.lang.Object ref = weightUnit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weightUnit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string weight_unit = 2;</code>
     * @param value The weightUnit to set.
     * @return This builder for chaining.
     */
    public Builder setWeightUnit(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      weightUnit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string weight_unit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightUnit() {
      weightUnit_ = getDefaultInstance().getWeightUnit();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string weight_unit = 2;</code>
     * @param value The bytes for weightUnit to set.
     * @return This builder for chaining.
     */
    public Builder setWeightUnitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      weightUnit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double ask_ ;
    /**
     * <code>optional double ask = 3;</code>
     * @return Whether the ask field is set.
     */
    @java.lang.Override
    public boolean hasAsk() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional double ask = 3;</code>
     * @return The ask.
     */
    @java.lang.Override
    public double getAsk() {
      return ask_;
    }
    /**
     * <code>optional double ask = 3;</code>
     * @param value The ask to set.
     * @return This builder for chaining.
     */
    public Builder setAsk(double value) {

      ask_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional double ask = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsk() {
      bitField0_ = (bitField0_ & ~0x00000004);
      ask_ = 0D;
      onChanged();
      return this;
    }

    private double mid_ ;
    /**
     * <code>optional double mid = 4;</code>
     * @return Whether the mid field is set.
     */
    @java.lang.Override
    public boolean hasMid() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional double mid = 4;</code>
     * @return The mid.
     */
    @java.lang.Override
    public double getMid() {
      return mid_;
    }
    /**
     * <code>optional double mid = 4;</code>
     * @param value The mid to set.
     * @return This builder for chaining.
     */
    public Builder setMid(double value) {

      mid_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional double mid = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMid() {
      bitField0_ = (bitField0_ & ~0x00000008);
      mid_ = 0D;
      onChanged();
      return this;
    }

    private double bid_ ;
    /**
     * <code>optional double bid = 5;</code>
     * @return Whether the bid field is set.
     */
    @java.lang.Override
    public boolean hasBid() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional double bid = 5;</code>
     * @return The bid.
     */
    @java.lang.Override
    public double getBid() {
      return bid_;
    }
    /**
     * <code>optional double bid = 5;</code>
     * @param value The bid to set.
     * @return This builder for chaining.
     */
    public Builder setBid(double value) {

      bid_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional double bid = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBid() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bid_ = 0D;
      onChanged();
      return this;
    }

    private double value_ ;
    /**
     * <code>optional double value = 6;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional double value = 6;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }
    /**
     * <code>optional double value = 6;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(double value) {

      value_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional double value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      value_ = 0D;
      onChanged();
      return this;
    }

    private double performance_ ;
    /**
     * <code>optional double performance = 7;</code>
     * @return Whether the performance field is set.
     */
    @java.lang.Override
    public boolean hasPerformance() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional double performance = 7;</code>
     * @return The performance.
     */
    @java.lang.Override
    public double getPerformance() {
      return performance_;
    }
    /**
     * <code>optional double performance = 7;</code>
     * @param value The performance to set.
     * @return This builder for chaining.
     */
    public Builder setPerformance(double value) {

      performance_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional double performance = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerformance() {
      bitField0_ = (bitField0_ & ~0x00000040);
      performance_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.protos.RealPricesRecord)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.protos.RealPricesRecord)
  private static final com.example.demo.protos.RealPricesRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.protos.RealPricesRecord();
  }

  public static com.example.demo.protos.RealPricesRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RealPricesRecord>
      PARSER = new com.google.protobuf.AbstractParser<RealPricesRecord>() {
    @java.lang.Override
    public RealPricesRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RealPricesRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RealPricesRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.protos.RealPricesRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

