// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dto/signup_request_dto.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public interface SignupRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.protos.SignupRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string password = 2;</code>
   * @return Whether the password field is set.
   */
  boolean hasPassword();
  /**
   * <code>optional string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>optional string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
