// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dto/signup_response_dto.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public final class SignupResponseDTOOuterClass {
  private SignupResponseDTOOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SignupResponseDTOOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_protos_SignupResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_protos_SignupResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035dto/signup_response_dto.proto\022\027com.exa" +
      "mple.demo.protos\"\255\001\n\021SignupResponseDTO\022\025" +
      "\n\010username\030\001 \001(\tH\000\210\001\001\022\025\n\010password\030\002 \001(\tH" +
      "\001\210\001\001\022\024\n\007balance\030\003 \001(\001H\002\210\001\001\022\033\n\016successMes" +
      "sage\030\004 \001(\tH\003\210\001\001B\013\n\t_usernameB\013\n\t_passwor" +
      "dB\n\n\010_balanceB\021\n\017_successMessageB8\n\027com." +
      "example.demo.protosB\033SignupResponseDTOOu" +
      "terClassP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_protos_SignupResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_protos_SignupResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_protos_SignupResponseDTO_descriptor,
        new java.lang.String[] { "Username", "Password", "Balance", "SuccessMessage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
