// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dto/signup_request_dto.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public final class SignupRequestDTOOuterClass {
  private SignupRequestDTOOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SignupRequestDTOOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_protos_SignupRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_protos_SignupRequestDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034dto/signup_request_dto.proto\022\027com.exam" +
      "ple.demo.protos\"Z\n\020SignupRequestDTO\022\025\n\010u" +
      "sername\030\001 \001(\tH\000\210\001\001\022\025\n\010password\030\002 \001(\tH\001\210\001" +
      "\001B\013\n\t_usernameB\013\n\t_passwordB7\n\027com.examp" +
      "le.demo.protosB\032SignupRequestDTOOuterCla" +
      "ssP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_protos_SignupRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_protos_SignupRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_protos_SignupRequestDTO_descriptor,
        new java.lang.String[] { "Username", "Password", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
