// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: entity/update_balance_request_entity.proto
// Protobuf Java Version: 4.29.3

package com.example.demo.protos;

public interface UpdateBalanceRequestEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.protos.UpdateBalanceRequestEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional double balance = 2;</code>
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   * <code>optional double balance = 2;</code>
   * @return The balance.
   */
  double getBalance();
}
